chore: Enable label and milestone automation (#247)

diff --git a/.github/workflows/pr-github-checks.yml b/.github/workflows/pr-github-checks.yml
--- a/.github/workflows/pr-github-checks.yml
+++ b/.github/workflows/pr-github-checks.yml
@@ -15,62 +15,94 @@ on:
       - milestoned
   workflow_dispatch:
 
+env:
+  PROJECT_NAME: "Huskies"
+  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  GH_REPO: ${{ github.repository }}
+  NUMBER: ${{ github.event.number }}
+  TITLE: ${{ github.event.pull_request.title }}
+  GH_HOST: github.com
+
+permissions: write-all
+
 jobs:
-  pr-milestone-check:
+  pr-milestone-project-check:
     runs-on: ubuntu-latest
     steps:
-      - name: Check for milestone
-        env:
-          MILESTONE: ${{ toJSON(github.event.pull_request.milestone) }}
+      - name: Set milestone
+        if: github.event.pull_request.milestone == null
         run: |
-          echo "${MILESTONE}" | jq -e '.!=null' || (echo "Milestone is not set"; exit 1)
+          # set milestone to the latest open milestone
+          latest_milestone=$(gh api \
+            -H "Accept: application/vnd.github+json" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            /repos/${GH_REPO}/milestones --hostname ${GH_HOST} | jq -r '.[]|.title' | sort -r | head -n 1)
+          # fail if there is no open milestone
+          if [ -z "$latest_milestone" ]; then
+            echo "No open milestone found"
+            exit 1
+          fi
+          gh pr edit ${{ github.event.number }} --milestone "${latest_milestone}"
 
   pr-label-check:
     runs-on: ubuntu-latest
     steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
+
+      - name: Add kind label based on PR title prefix
+        if: always()
+        run: |
+          # get title prefix
+          # get kind label
+          # check if kind label is the same as title prefix
+          # check if there is a kind label for the title prefix based on the mapping
+          # if label is missing, add the correct one
+          # if label is incorrect, remove it and add the correct one
+          #
+          prefix=$(echo "$TITLE" | grep -o '^[a-z]*')
+          kind_label=$( gh pr view "$NUMBER" --json labels -q '.labels[]|.name' | grep '^kind/' || true )
+          prefix_to_label_file=.github/workflows/titleprefix_to_label.json
+          correct_kind_label=$(cat $prefix_to_label_file | jq -r ".\"$prefix\"")
+          if [ -z "$kind_label" ]; then
+            echo "Adding $correct_kind_label label"
+            gh pr edit "$NUMBER" --add-label $correct_kind_label
+          elif [ "$kind_label" != "$correct_kind_label" ]; then
+            echo "Removing $kind_label label"
+            gh pr edit "$NUMBER" --remove-label $kind_label
+            echo "Adding $correct_kind_label label"
+            gh pr edit "$NUMBER" --add-label $correct_kind_label
+          fi
+
       - name: Check for area label
         if: always()
         run: |
-          gh api --jq '.labels.[].name' /repos/${{ github.repository }}/pulls/${{ github.event.number }} | \
+          gh api --jq '.labels.[].name' /repos/${REPO}/pulls/${NUMBER} | \
           grep -q '^area\/' || (echo "area label missing"; exit 1)
         env:
           GH_TOKEN: ${{ github.token }}
-
-      - name: Check for kind label
-        if: always()
-        run: |
-          gh api --jq '.labels.[].name' /repos/${{ github.repository }}/pulls/${{ github.event.number }} | \
-          grep -q '^kind\/' || (echo "kind label missing"; exit 1)
-        env:
-          GH_TOKEN: ${{ github.token }}
-
-      - name: Check if kind label matches pr title prefix
-        if: always()
-        run: |
-          kind_label=$( gh api --jq '.labels.[].name' /repos/${{ github.repository }}/pulls/${{ github.event.number }} | grep '^kind/')
-          kind_label_to_pr_title_prefix='{"kind/bug":"fix","kind/feature":"feat","kind/docs":"docs","kind/chore":"chore","kind/flaky-test":"test","kind/missing-test":"test","kind/failing-test":"test","kind/deps":"deps"}'
-          prefix=$(echo $kind_label_to_pr_title_prefix | jq -r ".\"$kind_label\"")
-          echo "${{ github.event.pull_request.title }}" | grep '^'$prefix || (echo "PR title should start with $prefix"; exit 1)
-        env:
-          GH_TOKEN: ${{ github.token }}
+          REPO: ${{ github.repository }}
+          NUMBER: ${{ github.event.number }}
 
       - name: Check that there is no do-not-merge label
         if: always()
         run: |
-          labels=$(gh api --jq '.labels.[]' /repos/${{ github.repository }}/pulls/${{ github.event.number }} )
+          labels=$(gh api --jq '.labels.[]' /repos/${REPO}/pulls/${NUMBER} )
           echo "Labels found: $( echo $labels | jq -r '.name' )"
 
           ! echo "$labels" | jq 'select(.name | startswith("do-not-merge"))' | jq -n "input.name"
         env:
           GH_TOKEN: ${{ github.token }}
+          REPO: ${{ github.repository }}
+          NUMBER: ${{ github.event.number }}
 
   pr-title-check:
     runs-on: ubuntu-latest
     steps:
       - name: Validate title
-        uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017
+        uses: amannn/action-semantic-pull-request@47b15d52c5c30e94a17ec87eb8dd51ff5221fed9
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GITHUB_TOKEN: ${{ github.token }}
         with:
           types: |
             deps
@@ -80,4 +112,3 @@ jobs:
             fix
             test
           requireScope: false
-          subjectPattern: ^([A-Z].*[^.]|bump .*)$
